name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up environment variables
      run: echo "Environment variables are set."
    - name: Run tests
      run: |
        pytest tests/

    