name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up environment variables
      run: echo "Environment variables are set."
      #example environment variables - you need ot set them in GitHub secrets!
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    - name: Run tests
      run: |
        pytest tests/

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/PROJECT_NAME:${{ github.sha }}


    # example deployment to Google Cloud Run
    # # Logowanie do Google Cloud
    # - name: Authenticate to Google Cloud
    #   uses: google-github-actions/auth@v1
    #   with:
    #     credentials_json: ...

    # # Wdrożenie na Google Cloud Run
    # - name: Deploy to Cloud Run
    #   run: |
    #     gcloud run deploy PROJECT_NAME \
    #       --image "gcr.io/YOUR_PROJECT_ID/..." \
    #       --platform managed \
    #       --region us-central1 \
    #       --allow-unauthenticated
    #   env:
    #     GOOGLE_CLOUD_PROJECT: ...
    #     GOOGLE_CLOUD_REGION: ...